language: generic
services:
    - docker

before_install:
    - docker build -t anastasiya108/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true anastasiya108/react-test npm test

after_success:
    - docker build -t anastasiya108/multi-client ./client
    - docker build -t anastasiya108/multi-nginx ./nginx
    - docker build -t anastasiya108/multi-server ./server
    - docker build -t anastasiya108/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to dockerhub
    - docker push anastasiya108/multi-client
    - docker push anastasiya108/multi-nginx
    - docker push anastasiya108/multi-server
    - docker push anastasiya108/multi-worker

#deploy:
#    provider: elasticbeanstalk
#    region: "ca-central-1"
#    app: "multi-docke"
#    env: "MultiDocke-env-1"
#    bucket_name: "elasticbeanstalk-ca-central-1-522650954375"
#    bucket_path: "docker-multi"
#    on:
#        branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY